name: BUG Report / BUG 反馈
description: 'Report a bug / 反馈一个 Bug'
labels: [Bug]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type / 问题类型
      options:
        - 'Game Crash / 游戏运行崩溃'
        - 'Launcher Crash / 启动器崩溃'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description / 问题描述
      description: |
        Clearly and in detail describe the issue you encountered.
        清晰，详细地描述出您所遇到的问题。
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log File / 日志文件
      description: |
        The crash page of the launcher will have a "Share Logs" button. Please upload the log provided by the launcher here.
        If your issue is related to a "Launcher Crash", you can find the "Share Launcher Logs" option in the launcher settings. Please upload the log archive provided by the launcher here.
        If your issue is related to a "Game Crash", you can use a file manager to navigate to ZL2's public directory and locate the "latest_game.log" file.
        启动器的崩溃页面会有“分享日志”按钮，请将启动器给出的日志上传在这里；
        如果您的问题属于“启动器崩溃”，您可以在启动器设置内找到“分享启动器日志”选项，请将启动器给出的日志压缩包上传在这里；
        如果您的问题属于“游戏运行崩溃”，您可以在文件管理器软件内进入 ZL2 的公有目录，找到 “latest_game.log” 文件。
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos / 截图或视频
      description: |
        Upload screenshots or videos from the most recent occurrence of the issue. This may help me identify the problem faster.
        上传最近一次遇到此问题的截图或者视频，可能会帮助我更快的确定问题。
    validations:
      required: false

  - type: textarea
    id: repetition
    attributes:
      label: Reproduction Steps / 复现步骤
      description: |
        Steps to reproduce the issue. Please be as detailed as possible to help me quickly locate the problem.
        复现问题的步骤，请尽量详细一些，方便我快速定位问题。
      placeholder: |
        1. xxx
        2. xxx
        ... *(steps to reproduce the issue / 复现问题的一些操作)*
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: android-version
    attributes:
      label: Android Version / Android 版本
      description: |
        ZL2 does not support running on devices with Android 7 or lower!
        ZL2 不支持运行在 Android 7 或更低版本的设备上！
      options:
        - '16'
        - '15'
        - '14'
        - '13'
        - '12'
        - '11'
        - '10'
        - '9'
        - '8'
    validations:
      required: true

  - type: input
    id: device-info
    attributes:
      label: Device Information / 设备信息
      description: |
        Providing detailed information about the device will help me troubleshoot the issue.
        提供设备的详细信息，有助于我排查问题。
      placeholder: Android 11, arm64
    validations:
      required: true